version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Docker/Dockerfile.local
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=simple_product_order_db;User Id=sa;Password=YourStrong@Password;Encrypt=False
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Password
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
