name: Deploy .NET Core 9 API to Local IIS

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Setup .NET 9 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.304'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build application
      run: dotnet build --configuration Release --no-restore

    - name: Publish application
      run: dotnet publish --configuration Release --no-build --output ./publish

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: api-publish
        path: ./publish

  deploy-to-iis:
    needs: build
    
    runs-on: self-hosted

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: api-publish
        path: ./publish

    - name: Deploy to IIS folder
      run: |
        $siteName = "simple-api" 
        $destinationPath = "D:\PIHC\Deployment\simple-api"

        # Stop the IIS Website
        Stop-Website -Name $siteName

        # Clear out the old files from the destination folder
        Get-ChildItem -Path $destinationPath | Remove-Item -Recurse -Force

        # Copy the new published files
        Copy-Item -Path "./publish/*" -Destination $destinationPath -Recurse -Force

        # Start the IIS Website
        Start-Website -Name $siteName
      shell: pwsh
